import type { Metadata } from "next"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import "./globals.css"

import "@/css/lib/lightbox/css/lightbox.min.css"
import "@/css/lib/owlcarousel/owl.carousel.min.css"
import "@/css/bootstrap.min.css"
import "@/css/style.css"

export const metadata: Metadata = {
  title: "Cidepym",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="es">
      <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
      </head>
      <body className={``}>
        <Header />
        {children}
        {/* <a href="#" className="btn btn-primary border-3 border-primary rounded-circle back-to-top"><i className="fa fa-arrow-up"></i></a> */}
        <Footer />
      </body>
    </html>
  )
}
